Fix container cannot access to AWS API
RequestError: send request failed
caused by: Post https://ec2.us-west-2.amazonaws.com/: x509: failed to load system roots and no roots provided